### ISSUE TITLE
uat_measure_ellip_phot.py --> ellipse sizes

### ISSUE THREAD

**Issue by Kyssuber** [rfinn/HalphaImaging#16]
For a given galaxy, the ellipse sizes for H-alpha and r-band cutouts often differ, making for inaccurate (and unsightly) radial profiles.

**Comment by rfinn** [comment]
this is because the ellipse size is scaled from what sextractor measures as R90.  This will be different for the R and Halpha images.  We should discuss with others, but I think this is ok as it is for now.
