### ISSUE TITLE
uat_HDIgroupflatfiles.py with 20180315 data

### ISSUE THREAD

**Issue by gammaspire** [rfinn/HalphaImaging#18]
Receive following error from line 82 (filter.append(t[3].rstrip('\n'))):
"list index out of range"

**Comment by rfinn** [comment]
I just reduced another night and didn't have this problem.  We should look at your exact issue to figure out what is going on.

**Comment by Kyssuber** [comment]
I think the error is exclusive to the 20180315 data, unfortunately. I am wondering whether the issue is with the header information.
