### ISSUE TITLE
Segmentation fits of galaxies?

### ISSUE THREAD

**Issue by Kyssuber** [rfinn/HalphaImaging#26]
uat_mask.py does not output any segmentation images -- only segmentation.fits, of which there is one -- so the "mask procedure" you created in Astro Tutorials is not effective when I try generalizing it to all pointing numbers. It could be a problem with how the code names the segmented file, so it is overwritten each time uat_mask.py is successfully run.

![screen shot 2018-08-29 at 1 28 44 pm](https://user-images.githubusercontent.com/39608848/44804512-84b61a80-ab8f-11e8-8ac1-44516f3b1e59.png)

**Comment by Kyssuber** [comment]
I should also mention I tried using the masked image corresponding to the galaxy pointing number, which is the reasoning for the "mask" name scheme. (Obviously, this method was ineffective, since the mask does not include object 1 unless specified by the user.)

**Comment by rfinn** [comment]
I think this is fixed.
